development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: statisfy_development
  pool: 5
  username: nickmalcolm
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: statisfy_test
  pool: 5
  username: nickmalcolm
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: statisfy_production
  pool: 5
  username: root
  password: